name: Flutter CI

on:
  push:

jobs:
  build:
    name: Eliverd Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Clone Eliverd repository
        uses: actions/checkout@v2
        with:
          path: 'eliverd'
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Doctor Flutter Repository
        run: flutter doctor -v
      - name: Show Flutter Version
        run: flutter --version
      - name: Fetch all dependencies on Flutter project
        run: flutter pub get
        working-directory: eliverd
      - name: Analyze Dart code
        run: flutter analyze
        working-directory: eliverd
      - name: Test Flutter project
        run: flutter test
        working-directory: eliverd
      - name: Build and export to apk from Flutter project
        run: flutter build apk
        working-directory: eliverd